apiVersion: 1
providers:
  - name: Default
    folder: Docker
    type: file
    disableDeletion: false
    editable: true
    updateIntervalSeconds: 10
    options:
      path: /var/lib/grafana/dashboards   # ← 디렉터리 경로

