apiVersion: 1
providers:
  - name: Default
    folder: Services              # ← 또는 Docker, 딱 하나만 사용
    type: file
    disableDeletion: false
    editable: true
    updateIntervalSeconds: 10
    options:
      path: /var/lib/grafana/dashboards   # 디렉터리 경로(파일 X)

