global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']   # localhost 대신 서비스명 권장

  - job_name: 'cadvisor'               # 대시보드가 job="cadvisor"를 기대함
    static_configs:
      - targets: ['cadvisor:8080']     # 같은 네트워크에서 서비스명:포트
